document.querySelector("#paragrafo").innerHTML="ALTERANDO O PRIMEIRO PARAGRAFO PELO QUERYSELECTOR IDENTIFICADOR";

document.querySelector(".paragrafo").innerHTML="ALTERANDO O SEGUNDO PARAGRAFO PELO QUERYSELECTOR CLASSE RETORNANDO APENAS O PRIMEIRO";

document.querySelectorAll(".paragrafo")[1].innerHTML="ALTERANDO O TERCEIRO PARAGRAFO COM QUERYSELECTOR ALL CLASSE NA POSIÇÃO 1."

document.querySelectorAll("p")[3].innerHTML="ALTERANDO O QUARTO PARAGRAFO COM QUERYSELECTOR ALL PEGANDO PELA TAG P NA POSIÇÃO 3."